lang: pt-br
project:
  type: website
  
    

website:
  page-navigation: true
  title: "Rpsi"
  repo-url: https://github.com/pablo-huascar/rpsi
  page-footer:
    left: "Esta página foi construída com [Quarto](https://quarto.org/)."
    right: 
      <img src="images/logo_pos.png" width="200"> 
      <img src="images/lappsie.png" width="200">
  navbar:
    align: center
    title: "Rpsi"
    background: "#FDFEFE"
    search: true
    collapse-below: lg
    left:
      - text: "Proposta"
        file: index.qmd
      - text: "Conteúdos"
        file: conteudos.qmd
    right: 
      - icon: github
      - href: https://github.com/pablo-huascar/rpsi
      - icon: "{{< fa brands github >}}"
        href: https://github.com/pablo-huascar/rpsi
      - text: "{{< fa brands github size=2x >}}"
        href: https://github.com/pablo-huascar/rpsi
      
        
  
  sidebar:
    - title: "Conteúdos"
      style: "floating"
      align: left
      contents:
        - conteudos.qmd
        - basico.qmd
        - trasnformacao.qmd
        - iteracao.qmd
        - importacao.qmd
        - graficos.qmd
        - dados_arrumados.qmd
        - regressao.qmd

    
    
format:
  html:
    code-link: true
    code-line-numbers: false
    theme: 
      - cosmo
      - styles.scss
    toc: true
    code-copy: true

editor: visual


