---
title: "Conteúdos da Oficina"
---

Até o momento, foram desenvolvidos seis módulos para a oficina "Introdução ao R para análise de dados em Psicologia". Em breve, serão acrescentadas discussões sobre estatística descritiva e sobre as análises mais básicas: correlação, test t, anova, qui-quadrado e regressão. Em cada módulo, você também vai encontrar um conjunto de exercícios que acompanha a oficina. Siga com as atividades no seu ritmo, mas é interessante que, a cada módulo, você tente responder o bloco de exercícios correspondente. Também aproveite a oportunidade para discutir com os seus colegas sobre os códigos utilizados.

## [Introdução ao R](basico.qmd)

Neste módulo é apresentado o mínimo necessário para se familiarizar com a linguagem básica do R. Neste caso, nem sempre há uma transposição do que é feito em software com interface gráfica, mas este passo inicial é importante para que se entenda como R funciona por si mesmo.

## [Transformação de dados](trasnformacao.qmd)

Antes de analisarmos os dados que colhemos, algumas tarefas são essenciais: criar variáveis a partir daquelas coletadas inicialmente, filtrar valores e arranjá-los de forma ascendente ou descendente. Eventualmente, também é necessário selecionar variáveis, renomeá-las e mudá-las de posição. Sumariar alguns resultados é, ainda, uma atividade importante nessa fase de manipulação dos dados. Todas essas tarefas podem ser feitas com o pacote `dplyr` e é sobre ele que vamos nos debruçar nesse módulo.

## [Iteração](iteracao.qmd)

No contexto do [tidyverse](https://www.tidyverse.org/){target="_blank"}, iteração diz respeito a executar repetidamente a mesma ação em diferentes objetos. É possível, por exemplo, com a função `summarise` calcular a média e o desvio padrão de várias colunas de uma só vez ou transformá-las com a função `mutate`. A iteração é importante porque evita copiar e colar funções mais de 2 vezes, o que pode gerar erros que se propagam no código. Essa é uma capacidade do tidyverse muito poderosa, contudo, dado o caráter introdutório da oficina, vamos nos deter na função `across`.

## [Importação de dados](importacao.qmd)

Trabalhar com os bancos de dados que acompanham o R e alguns pacotes foi muito divertido, mas é hora de analisar seus próprios dados. A importação de dados é uma tarefa simples, mas que pode ter nuances que demandam atenção. Vamos aprender a importar arquivos csv (valores separados por vírgula), csv2 (valores separados por ponto e vírgula), .sav (SPSS), .xlsx (Excel). Também teremos algumas dicas sobre como organizar os dados e os nomes das variáveis. Além disso, vamos aprender a exportar os dados no formato csv. Para tanto, vamos utilizar os pacotes `readr`, `haven` e `readxl`.

## [Gráficos](graficos.qmd)

Gráficos são uma ferramenta muito importante para explorar os dados assim como para tornar a apresentação de resultados mais amigável, de modo que não precisamos nos ater somente a aridez das tabelas. Para tanto, vamos trabalhar com uma ferramenta poderosa: o pacote `ggplot2`. Serão apresentadas funções para a criação de gráficos simples e, ainda, algumas que permitem controlar vários elementos da figura que se quer produzir.

## [Dados arrumados](dados_arrumados.qmd)

Este talvez seja o módulo que mais se distancia do cotidiano de pesquisadores de psicologia e de ciências humanas. Usualmente, trabalhamos com dados que nós coletamos e, ao importá-los ou alimentarmos planilhas, já os temos no formato *tidy* (arrumado). Este formato se refere ao seguinte:

1.  Cada variável é uma coluna; cada coluna é uma variável.
2.  Cada observação é uma linha; cada linha é uma observação.
3.  Cada valor é uma célula; cada célula é um único valor.

Contudo, não é incomum que trabalhemos com, por exemplo, bancos de dados públicos ou que não coletamos diretamente, de sorte que é essencial arrumá-los para que possamos executar nossas análises. Nesse sentido, vamos dar um pequeno passeio pela função `pivot_longer`

## [Regressão linear](regressao.qmd)

Regressão linear é uma análise estatística simples, mas é uma ferramenta que ajuda a resolver muitos problemas no cotidiano dos pesquisadores. Neste módulo, teremos noções básicas sobre esta ferramenta, bem como sobre a sua implementação no R. Além da função `lm()`, que está na base do R, vamos utilizar alguns pacotes do [tidymodels](https://www.tidymodels.org/){target="_blank"}. O [tidymodels](https://www.tidymodels.org/){target="_blank"} é um conjunto de ferramentas e pacotes que fornecem uma abordagem consistente e organizada para modelagem estatística e aprendizado de máquina, seguindo os princípios de organização e clareza do tidyverse. Ele facilita a construção, avaliação e ajuste de modelos estatísticos de forma eficiente e intuitiva.

::: callout-warning
A página da oficina está em construção e passando por constantes atualizações e revisões.
:::
